### ISSUE TITLE
Todo-show checks non source files

### ISSUE THREAD

**Issue by kikijiki** [jamischarles/atom-todo-show#24]
In my project todo results I'm getting a bunch of .ai (adobe illustrator files) and .pdn (paint.net) files under the XXX category, each thousands of characters long.

![1](https://cloud.githubusercontent.com/assets/784077/5235205/bff5878e-7835-11e4-95e3-7c9073963742.PNG)

![2](https://cloud.githubusercontent.com/assets/784077/5235203/b74ae714-7835-11e4-8aa0-1329ec76e75b.PNG)

**Comment by kikijiki** [comment]
I think it might do the trick.

**Comment by MRodalgaard** [comment]
fb99c3593c21ecb1583190df10ff0a510c92f28b adds truncation of matches longer then 120 chars.

When I add a non-source file to my project, the scan totally ignores the file and thereby no false matches. So I cannot reproduce what you are seeing. If it still exists, send me the file and I'll investigate a way to solve it.

**Comment by kikijiki** [comment]
Just tried it now, looks like it isn't solved.
![default](https://cloud.githubusercontent.com/assets/784077/7885421/b5fcbd44-065e-11e5-80fc-f6f86ef02dbb.PNG)

**Comment by MRodalgaard** [comment]
Not exactly pretty :)

Commit f0d763c1c1f64d0a1aa3e9a0da8a779469ed6c30 solves the wrapping of match texts, so it doesn't overlap with file paths (link text).

But do you have any suggestions to how we can avoid these false hits from binary data completely?

**Comment by kikijiki** [comment]
Have you seen this? https://github.com/bevry/istextorbinary

**Comment by MRodalgaard** [comment]
I think that is too much of an overhead for each file searched. And we can't look at comment scope (unless there is a special scope for binary) because that would exclude raw text, e.g. markdown documents with todos.

As I mentioned earlier; I am unable to reproduce this with any binary files I have, so could you attach one of the files you are exteriencing this with, so I can test it locally?

**Comment by kikijiki** [comment]
Just sent you a mail with it.

**Comment by mrodalgaard** [comment]
8c1d76c8d138f47a8e248eddd2580c3a407763f7 enforces a space after todos. This prevents false positives from the file you are referencing, thereby solving this issue better then checking for binary content on every match or just truncating long results.

**Comment by kikijiki** [comment]
Looks like that library just checks extension first and then some small chunks at the beginning or at the middle of the file, not really that much of a overhead since you're already using a regex with the full content of possibly fairly big files.
A space after the todo seems reasonable, but it depends on how people style their comments.
