### ISSUE TITLE
Feature Request: display TODOs in current file only

### ISSUE THREAD

**Issue by dwelle** [jamischarles/atom-todo-show#26]

**Comment by MRodalgaard** [comment]
Cannot see how this would be relevant.

**Comment by krilim** [comment]
If I open a file (or many) with rmate (over ssh) I had a bunch of files... In this case I want the shown TODOs from just the opened files and not the local dir that has nothing to do with the remote location.

In this case I think it's a good idea to have an option to search only opened files (or current).

**Comment by MRodalgaard** [comment]
That is a reasonable use case. Also I have found that having a huge project it makes sense to just look isolated at the todos for a subdirectory, where search only in open files would be enough. Would `todo-show:find-in-open-files` command pallette be sufficient?

**Comment by krilim** [comment]
I think so :-)
