### ISSUE TITLE
Enable wildcard in ignored path

### ISSUE THREAD

**Issue by Nox-404** [jamischarles/atom-todo-show#28]
It would be great to use wildcards in ignored path, so we can do things like :
`/*/vendor/` or `*.binary` or even more complex regexp

**Comment by t3asdev** [comment]
This already shoud work. Have a look at https://github.com/jamischarles/atom-todo-show/issues/30#issuecomment-73212662
Is there any need for an own package-setting "todo-show.ignoreThesePaths" anymore ??
