### ISSUE TITLE
Ignore `-->` at end of HTML comments

### ISSUE THREAD

**Issue by halleycarleton** [jamischarles/atom-todo-show#29]
When a TODO is added to a one line html comment you end up with `-->` at the end of the TODO text. It would be nice if this were automatically removed.

Not a huge deal, as it doesn't really affect readability, it would just be nice.

**example**
```html
<header>
 <!-- TODO: Finish header -->
</header>
```
The TODO shows up as `Finish header -->`

**Comment by superlukas** [comment]
Same goes for CSS' `*/`.

I'm not great with regular expressions, but a positive lookahead should fix this. Something like `(?=.*(\*\/|-->)$)?` maybe.

**Comment by jamischarles** [comment]
My initial concern was the complexity of doing this across languages. I suppose we could start and do it for html, CSS and js. 

I'd be happy to review a PR with this, though I'd want some unit tests with it. 

I am not using atom at the moment (trying out vim) so I probably won't be building this feature in the near future.

**Comment by superlukas** [comment]
@jamischarles You're gonna love this: https://en.wikipedia.org/wiki/Comparison_of_programming_languages_%28syntax%29#Comments

**Comment by MRodalgaard** [comment]
I want to keep the regexes in config as simple as possible, so before returning the match it internally strips known block comment endings for the major languages; C (*/), HTML, PowerShell, Haskell, Lua. This will hopefully cover over 90% of the languages used, where this is a "problem".
