### ISSUE TITLE
Ignore path separators not cross platform

### ISSUE THREAD

**Issue by tdolsen** [jamischarles/atom-todo-show#30]
I had a bit of a struggle excluding my node_modules and similar from the Todo list. Turned out it was because the default settings used linux style path separators, and I am currently on win32.

My solution was to overwrite the default ignore paths with windows path separators.

```cson
  'todo-show':
    'ignoreThesePaths': [
      '\\node_modules'
      '\\vendor'
      '\\bower_components'
    ]
```

While this works at the moment does it make it hard for me to port my settings across computers and platforms. (E.g. using [atom-sync-settings](https://github.com/Hackafe/atom-sync-settings).)

Ideally the configs should use linux style path separators, and the package should determine if they need to be converted to win style.

**Comment by t3asdev** [comment]
Im running into the same Problem.
But by looking at the source i found that todo-show is internally using atom.project.scan (which is also used by the core-package "find-and-replace" i think). This API-Call ignores files and folders set by atoms core setting "Ignored Names". If you additionally check "Exclude VCS Ignored Paths" then all entries in your local-project-gitignore file are gonna ignored too. 

![atom-core-ignores](https://cloud.githubusercontent.com/assets/930604/6077233/19af6b18-aded-11e4-9a32-f1588f260fca.png)

This should be platform independent(works for me on my windows machine) so you dont have to add "todo-show.ignoreThesePaths" which is not.

This should be better documented in the README.

**Comment by jamischarles** [comment]
I accept PRs :)

**Comment by andischerer** [comment]
PR send ;)

**Comment by jamischarles** [comment]
Should be fixed now
