### ISSUE TITLE
.gitignore is not used for ignored paths

### ISSUE THREAD

**Issue by tdolsen** [jamischarles/atom-todo-show#31]
Although I can't find any reference to the functionality responsible for omitting `.gitignore` paths in the source, is it stated in the readme that it should do so.

I don't know if the feature is missing, if this has something to do with win32 path separators (as in issue #30), or if there is anything else.

But this feature would be much appreciated! :+1:

**Comment by jamischarles** [comment]
Should be fixed by the PR
