### ISSUE TITLE
Depreciated item - stylesheets/show-todo.less

### ISSUE THREAD

**Issue by danward79** [jamischarles/atom-todo-show#36]
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension. If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by jamischarles** [comment]
This still happening?

**Comment by danward79** [comment]
Ah, it looks like for some reason Atom was not automatically updating from 0.6.0. So I missed the fix. Manually Uninstalled and Re-Installed now to fix. Thanks

**Comment by MRodalgaard** [comment]
Can this be closed?

**Comment by danward79** [comment]
Yes,
