### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by marshallbu** [jamischarles/atom-todo-show#39]
Did the settings for this go away?

![settings_-__users_mupshu_projects_nike-plus-web-prerender_-_atom](https://cloud.githubusercontent.com/assets/607054/6234668/84a7ec68-b691-11e4-942d-27c70ac6fd74.png)

**Comment by marshallbu** [comment]
Eh, adding the setting manually to my config.cson seems to do what I need, I'll go this route.

**Comment by jamischarles** [comment]
They "should" still be there...

**Comment by marshallbu** [comment]
It may have just been my set up, no worries!
