### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by dbperez** [jamischarles/atom-todo-show#40]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
ShowTodoView.openPath (/Users/bperez/.atom/packages/todo-show/lib/show-todo-view.coffee:260:9)
```

**Comment by jamischarles** [comment]
Do you have the newest version? This should be resolved with most recent
update.

**Comment by dbperez** [comment]
@jamischarles 
Thanks for the quick response. Looks like it is indeed resolved. 
Closing issue.

Thanks!
