### ISSUE TITLE
todo-show throwing errors

### ISSUE THREAD

**Issue by JnBrewsterGT** [jamischarles/atom-todo-show#42]
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 9 timesCreate Issue on todo-show repo
Atom.Object.defineProperty.get - /Applications/Development/Atom.app/Contents/Resources/app/src/atom.js:54:11
ShowTodoView.openPath - /Users/jb259/.atom/packages/todo-show/lib/show-todo-view.coffee:260:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 9 timesCreate Issue on todo-show repo
Atom.Object.defineProperty.get - /Applications/Development/Atom.app/Contents/Resources/app/src/atom.js:54:11
ShowTodoView.moveCursorTo - /Users/jb259/.atom/packages/todo-show/lib/show-todo-view.coffee:269:25

**Comment by ericcirone** [comment]
Getting the same thing
