### ISSUE TITLE
todo-show has no settings on Windows

### ISSUE THREAD

**Issue by Stickiler** [jamischarles/atom-todo-show#44]
I've got the latest version of todo-show installed, and the latest version of Atom, on windows, and going to the settings for todo-show, there's no entry for changing the regex to search for.
On my Macbook with the same versions installed, the settings entry is there correctly.

**Comment by MRodalgaard** [comment]
I am unable to reproduce this using Atom 0.198.0 on Windows 7. Do you still see this behaviour?

**Comment by Stickiler** [comment]
It seems somewhere along the line this has been fixed. Thanks anyway!
