### ISSUE TITLE
Add DEBUG to the search / let users define patterns

### ISSUE THREAD

**Issue by funkyfuture** [jamischarles/atom-todo-show#45]
to me it is common to use DEBUG in sources at a point where either debugging must be done (in opposite to FIXME it rather means that the causes of an error should be looked for at this point) or that something is temporarily inserted to debug.

but propably it's better to let the users define what shuld be looked for via configuration.

**Comment by MRodalgaard** [comment]
Hi @funkyfuture ,

Custom search queries / regexes was added in dd6a912875509e9c66337431d3727e98183f0982 and is also included in latest published release.

Add the following to your `config.cson` (complemented by the other regexes you want to find):
```
"todo-show":
  findTheseRegexes: [
    'DEBUGs'
    '/DEBUG:?(.+$)/g'
  ]
```

**Comment by funkyfuture** [comment]
mille grazie.
