### ISSUE TITLE
Use activationCommands instead of activationEvents

### ISSUE THREAD

**Issue by d4k0** [jamischarles/atom-todo-show#46]
Since the update to Atom 0.189.0 I get the following deprecation warning (the screenshot is from a new profile with only atom-todo-show installed):

![Deprecation warning](https://i.imgur.com/bJbMFKD.png)

It would be nice if this could be fixed.

**Comment by jamischarles** [comment]
See this from the readme:

I no longer use Atom as my primary editor. Let me know if you want to share publish rights on this repo, or have shared git access. I don't have the time to keep up development on this repo anymore. I will gladly share access to the repo and will review PRs every few months.

**Comment by d4k0** [comment]
Ah, I didn't see this. I was able to fix the cause of the deprecation warning, but then new deprecation warnings appeared which require some more sophisticated changes regarding the config, so I will probably search for another solution.
