### ISSUE TITLE
Project.getPath is deprecated.

### ISSUE THREAD

**Issue by garralab** [jamischarles/atom-todo-show#48]
Use ::getPaths instead
```
Project.getPath (C:\Users\Alessandro Garagnani\AppData\Local\atom\app-0.190.0\resources\app\src\project.js:585:12)
<unknown> (C:\Users\Alessandro Garagnani\.atom\packages\todo-show\lib\show-todo-view.coffee:151:59)
```

Above it's the automatic issue report for this warning. Since in my case Ignore Path is not working I wonder if this could be the reason

**Comment by MRodalgaard** [comment]
This package uses [ignore](https://github.com/kaelzhang/node-ignore) for the ignore paths, which syntax is a little different then gitignore. The deprecation warning has no functional effect (yet).

Try adding this (prepending `*`) to your config.cson:

```
"todo-show":
  ignoreThesePaths: [
    "*/node_modules/"
    "*/vendor/"
    "*/bower_components/"
  ]
```

Commit 771b6c08fc58a09778c6fe1baa3aff1c369516a9 should fix the default ignore values and deprecation warning.
