### ISSUE TITLE
Feature: Add "HACK:" to default list

### ISSUE THREAD

**Issue by KylePDavis** [jamischarles/atom-todo-show#55]
The "HACK" prefix seems to be another fairly common comment tag that would make a good addition to the current defaults.

I'll make a PR if you'd like.

**Comment by MRodalgaard** [comment]
@KylePDavis, you are right. It would probably be a good idea to use the same defaults as the atom bundled [language-todo](https://github.com/atom/language-todo). That means adding `IDEA`, `NOTE` and `REVIEW` as well.

I'm open for PR's with test cases, but I'm currently thinking of a more transparent and condensed way of defining the regexes through config. Maybe two arrays; one with regexes and one with their titles.

**Comment by KylePDavis** [comment]
@MRodalgaard, even better. Maybe we could reuse the pattern from [language-todo/grammars/todo.cson#L6](https://github.com/atom/language-todo/blob/1d02b3349b33e0c90785080a724d588ea85b9217/grammars/todo.cson#L6) as the default then.

As for improving the config I'd recommend using an Object rather than two arrays. The keys could be the titles and the values could be the corresponding patterns.

**Comment by MRodalgaard** [comment]
I don't see how we could use `(?<!\\w)@?(TODO|FIXME|CHANGED|XXX|IDEA|HACK|NOTE|REVIEW)\\b` and still be extendable via config with custom regexes.

I looked at the object config solution, but kinda disliked the way it was presented in Settings:

![screen shot 2015-05-21 at 20 01 14](https://cloud.githubusercontent.com/assets/659763/7755433/357651b4-fff4-11e4-8d9d-08569f56c5f6.png)
### vs
![screen shot 2015-05-21 at 20 05 22](https://cloud.githubusercontent.com/assets/659763/7755490/bff2a8f6-fff4-11e4-84c2-b6cdfcbe5471.png)

Remember there are going to be 8 entrances total now. In config.cson the object solution probably looks a little cleaner than the two arrays. What do others think?

**Comment by KylePDavis** [comment]
@MRodalgaard, you're right that we can't use their RegExp directly. I just meant that that they have a decent list and we should do something similar.

As for the config, I think I prefer the object solution in both `config.cson` and the UI. I think the colocation of titles and patterns makes the UI a little more obvious in both cases.

**Comment by MRodalgaard** [comment]
Yes. Use the same list of regexes as [language-todo](https://github.com/atom/language-todo) and change the regex list in config to an object (key: title, value: regex).

Do you want to make a PR for this?

**Comment by KylePDavis** [comment]
Sure. I can do it.

**Comment by KylePDavis** [comment]
Well I tried to work on this and I'm having a weird issue.

When I describe the config like this:
```coffee
  config:
    patterns:
      type: 'object'
      properties:
        fixme:
          title: 'FIXMEs'
          type: 'string'
          default: 'FIXME:?(.+$)'
```

It works the first time but everything is after a reload.

The first time around seems to save a config that looks like this:
```coffee
  "todo-show":
    patterns:
      {}
```

Which is valid but it is interpreted to mean no RegExps. This seems correct but I'm not sure why Atom is writing out an empty object in the first place

Any idea how to make Atom do what we want here?

**Comment by MRodalgaard** [comment]
When I use that config description I also get an empty object for patterns in my config.cson, though `atom.config.get('todo-show.patterns')` still spits out the old default; `{fixme: "/FIXME:?(.+$)/g"}`. Seems to be something weird with objects in config. When opening Settings again the default is gone.

[The config example](https://atom.io/docs/api/v0.201.0/Config) doesn't use multiple key-values, default or title. At first I added the default as an object to patterns and it seemed much cleaner, but documentation suggests using properties for sub options.

Writing all default patterns to user config using `atom.config.set` at startup if pattern is not set could be another solution.

**Comment by KylePDavis** [comment]
I tried using a `default` Object originally like you had but you get less control over the titles and it has the same issue so I eventually switched it over to what I pasted earlier.

I considered using `atom.config.set` as a workaround but that seems like a bit of a hack and it would interfere with users getting updated defaults in the future.

I hope that we can figure out what's really going on here because I suspect that either a) we're doing it wrong or, b) there's an issue in atom somewhere and we should make a PR for it.

**Comment by MRodalgaard** [comment]
So I played around with the config settings for a while and searched for similar observations (see links below). But I did not come to a solid solution using objects.

@KylePDavis; I agree that the object approach is the more correct way, but it gets complicated fast when considering extensibility, overriding defaults and support in settings-view. Also that what we really want is an array of objects. The two arrays approach is just that much simpler to implement (less error prone) and easier for the user to grasp (you hear me giving up a little ;d). It is simply no good that the regexes can't be seen/set through Settings by the user.

Just extending the current solution with the new regexes could also be a solution for now, which would also prevent breaking backwards compatibility.

What do you think. Do we want to spent more time on this?


Reported something similar: https://github.com/atom/settings-view/issues/518

Objects in config will eventually be better presented to the user (add/remove entries): https://github.com/atom/settings-view/pull/52

Is also seeing an empty object, though his scenario is a little different: https://discuss.atom.io/t/config-vars-of-type-object-get-lost-ignore-schema/14497

**Comment by KylePDavis** [comment]
@MRodalgaard: Thanks for the research into this. I'll just update the RegExps for now and we can revisit using an Object for the config once there is better support for them.
