### ISSUE TITLE
Key binding conflict with Atom core

### ISSUE THREAD

**Issue by kankaristo** [jamischarles/atom-todo-show#56]
`ctrl-shift-t` is bound to `pane:reopen-closed-item` (re-open closed tab).

**Comment by MRodalgaard** [comment]
Would `alt-shift-t` be better on windows and linux?

**Comment by kankaristo** [comment]
Yeah, that would work. :+1:

That doesn't conflict with anything on Linux, and I *think* it's free on Windows as well.
