### ISSUE TITLE
Include line number

### ISSUE THREAD

**Issue by rthijssen** [jamischarles/atom-todo-show#59]
It would be great if you included the line number to the filename.

Example:
```
My TODO note   src/directory/filename.c:11
```

The main thought behind this is that it would make the .md file that you generate way more useful.

**Comment by MRodalgaard** [comment]
Seems like a good idea and really easy to add. Though I'm not fully satisfied with the overall look of the markdown output in the first place. Do you have any suggestions to how we can improve this further?

**Comment by rthijssen** [comment]
Although I quite like the current format of the markdown output (easy to send someone a list of notes after a code review) I can understand you might want to implement a second export format.

The only suggestion I can think of is to provide a second format that used [markdown tables](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables) which would make the output similar to your in-Atom view.

**Comment by MRodalgaard** [comment]
I do not like markdown tables, since they are horrible to read in raw text. I don't think we need a second export format, just wanted to improve a little on the current, since I find it hard to separate text from path in rendered format. I think maybe the markdown line I wrote above might be the best of both worlds. Disagree?

**Comment by rthijssen** [comment]
Fair enough. As mentioned before I quite like the current output format and your suggestion to change the format for the file name (and line number) makes sense. Looking forward to the next release! Thanks.

**Comment by rthijssen** [comment]
Hey mate, just wanted to let you know that the latest release is based on commit `80cb71a` and not `8caa43b` which contains the line numbers and new output format. I'm not sure if this is intentional or not but though I should mention it.

**Comment by mrodalgaard** [comment]
@rthijssen; v0.13.0 is published now.
