### ISSUE TITLE
TODO found outside comment block

### ISSUE THREAD

**Issue by krilim** [jamischarles/atom-todo-show#61]
This line:

```define("_JS_TODO_ALERT_", "javascript:alert(&quot;TODO&quot;);");```

is marked as a TODO even if it isn't.

**Comment by mrodalgaard** [comment]
Would the regex `'/\b@?TODO:?\s(.+$)/g'` result in a better match, where a space is required after an optional semicolon?

We are not looking at scope, since we do not want to only target comments, but also todos in raw text (e.g. markdown, text, json).

**Comment by krilim** [comment]
I suppose

**Comment by mrodalgaard** [comment]
Also see #24.
