### ISSUE TITLE
Use Atom's build configuration Window

### ISSUE THREAD

**Issue by jonnitto** [jamischarles/atom-todo-show#63]
Not everybody can get the settings right for the ignored path/file. It would be great to have a settings tab (like https://atom.io/packages/color-picker) where you can edit the ignored files and paths

**Comment by mrodalgaard** [comment]
Uhm, you closed this again?

The todo-show package has an `Ignore These Paths` string array option. What are you saying [color-picker](https://atom.io/packages/color-picker) are doing different?
