### ISSUE TITLE
Update default regex to recognize 'todo(username)'

### ISSUE THREAD

**Issue by phumke** [jamischarles/atom-todo-show#64]
An additional todo/fixme/etc convention is to include the username of the person who wrote the todo within parenthesis right after the todo.  Would you be interested in updating the regex to include this search pattern as part of the defaults?

Adding `(\\(.*\\))?` to each of the patterns should do it, for example: `/\\b@?TODO(\\(.*\\))?:?\\s(.+$)/g`

The one downside is that now there would be two matched groups that should be displayed within the output instead of just one.

**Comment by mrodalgaard** [comment]
I'm not sure I completely understand this pattern.

If you include a name in parenthesis now, it will be included just fine in the matched group. But I think `git blame` would be more suitable for identifying this.

Please elaborate.

**Comment by mrodalgaard** [comment]
Closed because of missing additional information and I do not think it is relevant enough. Using `git blame` would be the way to go.
