### ISSUE TITLE
Projects: Add check for duplicate entries

### ISSUE THREAD

**Issue by scherii** [jamischarles/atom-todo-show#67]
Hi!

I use two folders in my (WordPress) projects:
* one is the theme directory (main work is done in here)
* the other is the whole project, which (amongst others) contains the theme directory

It would be nice if there was a check for duplicate entries:
![Screenshot](http://i.imgur.com/wCURjZl.png)

**Comment by mrodalgaard** [comment]
I think you are better off adding the files or folder to `todo-show. ignoreThesePaths`. It's easy to filter out duplicates, but theres no way to decide which of the two found files are the one that should be shown and linked to the user.

Symlinks inside a project does not show multiple todos.

**Comment by scherii** [comment]
Never thought about to symlink this, thanks! :+1: 

And I'm sorry, I must've overlooked the [config part](https://github.com/jamischarles/atom-todo-show#config) in the readme :confused:
