### ISSUE TITLE
Request: Persistent panel resizing

### ISSUE THREAD

**Issue by dsifford** [jamischarles/atom-todo-show#71]
Great work on this so far! 

I was curious if it might be possible to make the todo panel width persist after manually resizing? 

I currently run a vertical monitor for writing code, so you can imagine that the default width takes up quite a bit of real estate and it gets tedious having to always resize the panel after toggling.

Thanks again for your hard work!

**Comment by mrodalgaard** [comment]
Will be included in next release.

Also with a vertical monitor you might consider using `openListInDirection: down`.

**Comment by dsifford** [comment]
Awesome, thanks!
