### ISSUE TITLE
Respect imdone syntax

### ISSUE THREAD

**Issue by amiuhle** [jamischarles/atom-todo-show#74]
After reordering tasks with [imdone-atom](https://github.com/imdone/imdone-atom), a priority is appended like this: `TODO:10`. After this, todo-show doesn't recognize tasks any more.

Adjusting the regular expressions as follows would fix this:

```javascript
/\b@?TODO(?::?(?:\d*))\s(.+$)/g
```

I tested this in my own settings. If you're willing to merge, I'll create a pull request and add some specs.

**Comment by mrodalgaard** [comment]
Thanks for reporting. I have improved the default regex to respect this.

**Comment by amiuhle** [comment]
Thanks!

**Comment by piascikj** [comment]
@mrodalgaard and @amiuhle Thanks for helping it play nice with imdone! :+1: :beers:
