### ISSUE TITLE
Not follow symlinks

### ISSUE THREAD

**Issue by ITler** [jamischarles/atom-todo-show#77]
Is it possible to tell the plugin to not follow symlinks when looking for Todos?

If not, this is a enhancement request :)

Thank you
ITler

**Comment by mrodalgaard** [comment]
[todo-show](https://github.com/jamischarles/atom-todo-show) uses `atom.workspace.scan` (same as e.g. the find-and-replace package) which respects the Atom Core Setting `Follow symlinks`. You can find this flag inside Atom Settings:

<img width="528" alt="screen shot 2015-09-09 at 19 52 32" src="https://cloud.githubusercontent.com/assets/659763/9769756/57cf268e-572c-11e5-9917-57663cd4b6a3.png">

**Comment by ITler** [comment]
Nice, thanks
