### ISSUE TITLE
Put token classname for parent element contains todo

### ISSUE THREAD

**Issue by VitaliyR** [jamischarles/atom-todo-show#78]
Hello. Currently I'm highlighting with green color in my syntax theme only TODO (or FIXME) word and can't highlight the actual text of todo (which I'm really wanna) because it is coming right after .todo as text node and I can't apply styles for it.

```
span.comment
  span.todo
    TODO
  : test (just an text node)
```

Maybe it is possible to add a feature which would be add to that parent .comment node one more class which would show that this node contains todo inside?

**Comment by mrodalgaard** [comment]
Atom has an out-of-the-box [included package](https://github.com/atom/language-todo), which adds syntax highlighting to TODO, etc.

todo-show is just about scanning the workspace and showing results with no modifications of the original text, so I do not think this feature will be added.

**Comment by VitaliyR** [comment]
@mrodalgaard thanks a lot, didn't knew about that, sorry :)
